### ISSUE TITLE
No module named 'aiohttp'

### ISSUE THREAD

**Issue by aubreyskingdom** [NDDDDDDDDD/TrackerChecker#12]
I'm getting the following error when attempting to run this:

line 2, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by NDDDDDDDDD** [comment]
try `pip install aiohttp`

**Comment by aubreyskingdom** [comment]
That worked, thanks!

**Comment by NDDDDDDDDD** [comment]
Great!
