### ISSUE TITLE
Tracker message changes

### ISSUE THREAD

**Issue by mokahless** [NDDDDDDDDD/TrackerChecker#14]
The following are being picked up as "open" due to changes in the sites:

soulvoice: This seems to be an issue with ?sitelanguage=6 no longer redirecting to an English version.

hdarea: hdarea seems to have the proper "registration is currently disabled" text on the linked page. But after a few retests, I'm still getting a message that it's open. I suspect it has something to do with their cloudflare browser checks.

**Comment by NDDDDDDDDD** [comment]
will get to it soon, sorry for the delay
