### ISSUE TITLE
Where Can I see List of Trackers Before Making A Request?

### ISSUE THREAD

**Issue by Hobbes-Is-Real** [NDDDDDDDDD/TrackerChecker#15]
Where Can I see List of Trackers Before Making A Request?

Thank you for writing this script!!!!!

**Comment by NDDDDDDDDD** [comment]
Hello and thank you!
Updated the current list for supported trackers, also made a new file in my github repo
https://github.com/NDDDDDDDDD/TrackerChecker/blob/main/trackers.txt

**Comment by Hobbes-Is-Real** [comment]
Thank you!

Can I give a feature suggestion?  the ability to send a daily / weekly auto
scheduled email summary.

In addition to setting the frequency also have a setting to auto send an
update on all major holidays as many trackers offer holiday (Easter /
Christmas / New Years / Chinese New Year / etc...) open enrollment events.
