### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by bulletproof2k** [NDDDDDDDDD/TrackerChecker#16]
E:\DEV\Py\trackerchecker>trackerchecker.py
Traceback (most recent call last):
  File "E:\DEV\Py\trackerchecker\trackerchecker.py", line 2, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by NDDDDDDDDD** [comment]
try 
pip install aiohttp
if you get the issue again for the other modules, re write that but with the module name
