### ISSUE TITLE
More trackers to consider adding

### ISSUE THREAD

**Issue by kaizensh** [NDDDDDDDDD/TrackerChecker#5]
- https://blutopia.xyz/
- https://www.torrentleech.org/
- https://hd-torrents.org/
- https://filelist.io/
- https://passthepopcorn.me/
- https://iptorrents.com/
- https://nebulance.io/
- https://anthelion.me/
- https://uhdbits.org/
- https://digitalcore.club/
- https://hd-space.org/
- https://tv-vault.me/
- https://sdbits.org/
- https://animebytes.tv/
- https://desitorrents.tv/
- https://bithumen.be/
- https://www.myanonamouse.net/
- https://redacted.ch/
- https://orpheus.network/
- https://gfxpeers.net/
- https://cgpeers.to/
- https://bitspyder.net/
- https://www.empornium.is/
- https://www.enthralled.me/
- https://www.happyfappy.org/
- https://femdomcult.org/
- https://milkie.cc/

**Comment by AktasC** [comment]
These could be easily added thourgh #4

**Comment by NDDDDDDDDD** [comment]
Thank you! Added the ones with valid error messages since it's needed
