### ISSUE TITLE
[BUG] Connection error 

### ISSUE THREAD

**Issue by Ramzh** [NDDDDDDDDD/TrackerChecker#9]
Upon choosing 1 it gives the following:

![image](https://user-images.githubusercontent.com/20802073/213460447-e381ada7-ac80-4b61-bb03-36b9e73f2dff.png)

**Comment by NDDDDDDDDD** [comment]
removed the tracker for now, thanks for brining it to my attention

**Comment by Ramzh** [comment]
> removed the tracker for now, thanks for brining it to my attention

Might be worth using a try-catch/except and log the sites/errors in a log file. This is the error I got today 

![image](https://user-images.githubusercontent.com/20802073/213653039-bd57ba35-3246-4631-981b-405e0890c383.png)
